unit frmVisListRac;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  StdCtrls, Mask, ToolEdit, CurrEdit;

type
  TfVisListRac = class(TForm)
    PrezzoVendita: TRxCalcEdit;
    L6: TRxCalcEdit;
    L1: TRxCalcEdit;
    L2: TRxCalcEdit;
    L3: TRxCalcEdit;
    L4: TRxCalcEdit;
    L7: TRxCalcEdit;
    L8: TRxCalcEdit;
    L9: TRxCalcEdit;
    L10: TRxCalcEdit;
    Label1: TLabel;
    Label2: TLabel;
    Label3: TLabel;
    Label4: TLabel;
    Label5: TLabel;
    Label6: TLabel;
    Label7: TLabel;
    Label8: TLabel;
    Label9: TLabel;
    Label10: TLabel;
    Label11: TLabel;
    L5: TRxCalcEdit;
    Label12: TLabel;
    L11: TRxCalcEdit;
    RxCalcEdit3: TRxCalcEdit;
    RxCalcEdit4: TRxCalcEdit;
    RxCalcEdit5: TRxCalcEdit;
    RxCalcEdit6: TRxCalcEdit;
    RxCalcEdit7: TRxCalcEdit;
    RxCalcEdit8: TRxCalcEdit;
    RxCalcEdit9: TRxCalcEdit;
    RxCalcEdit10: TRxCalcEdit;
    RxCalcEdit11: TRxCalcEdit;
    RxCalcEdit12: TRxCalcEdit;
    RxCalcEdit13: TRxCalcEdit;
    RxCalcEdit14: TRxCalcEdit;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  fVisListRac: TfVisListRac;

implementation

{$R *.DFM}

end.
