object fMostraFoto: TfMostraFoto
  Left = 182
  Top = 101
  Width = 544
  Height = 375
  Caption = 'Foto di Articolo'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object iFotoArt: TImage
    Left = 0
    Top = 0
    Width = 536
    Height = 348
    Align = alClient
  end
end
